# Generated by Django 4.0.4 on 2022-06-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=35, verbose_name='Тегі')),
                ('patronym', models.CharField(max_length=35, verbose_name='Әкесінің аты')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Ұялы телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтасы')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofbirth', models.DateField(verbose_name='Туған күні')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Қала')),
                ('IIN', models.CharField(max_length=20, verbose_name='ЖСН')),
                ('patronym', models.CharField(max_length=35, verbose_name='Әкесінің аты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Қолданушы')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Топтың аты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Топтың қысқаша')),
                ('day', models.CharField(choices=[('Дүйсенбі', 'Дүйсенбі'), ('Сейсенбі', 'Сейсенбі'), ('Сәрсенбі', 'Сәрсенбі'), ('Бейсенбі', 'Бейсенбі'), ('Жұма', 'Жұма'), ('Сенбі', 'Сенбі'), ('Жексенбі', 'Жексенбі')], max_length=255, verbose_name='Күн')),
                ('hours', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=255, verbose_name='Сағат')),
                ('filled', models.IntegerField(default=0, verbose_name='Неше оқушы бар')),
                ('max_available', models.IntegerField(default=30, verbose_name='Максималды оқушылар саны')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Оқушылар')),
            ],
        ),
    ]
