# Generated by Django 4.0.4 on 2022-06-01 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='day',
            field=models.CharField(choices=[('Дүйсенбі', 'Дүйсенбі'), ('Сейсенбі', 'Сейсенбі'), ('Сәрсенбі', 'Сәрсенбі'), ('Бейсенбі', 'Бейсенбі'), ('Жұма', 'Жұма'), ('Сенбі', 'Сенбі'), ('Жексенбі', 'Жексенбі')], default='d', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='filled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='hours',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], default='d', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='max_available',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
