# Generated by Django 4.0.4 on 2022-06-01 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_day_group_description_group_filled_group_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
