# Generated by Django 4.0.4 on 2022-06-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IIN',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='patronym',
            field=models.CharField(default='d', max_length=35),
            preserve_default=False,
        ),
    ]
