# Generated by Django 4.0.4 on 2022-06-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='none', upload_to='images'),
            preserve_default=False,
        ),
    ]
