# Generated by Django 4.0.4 on 2022-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Жабылу уақыты'),
        ),
    ]
