# Generated by Django 4.0.4 on 2022-06-03 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_iin_profile_patronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
