# Generated by Django 4.0.4 on 2022-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='none', upload_to='images', verbose_name='Суреті'),
            preserve_default=False,
        ),
    ]
