# Generated by Django 4.0.4 on 2022-06-03 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_rename_age_profile_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=35, verbose_name='Тегі')),
                ('patronym', models.CharField(max_length=35, verbose_name='Әкесінің аты')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Ұялы телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтасы')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='day',
            field=models.CharField(choices=[('Дүйсенбі', 'Дүйсенбі'), ('Сейсенбі', 'Сейсенбі'), ('Сәрсенбі', 'Сәрсенбі'), ('Бейсенбі', 'Бейсенбі'), ('Жұма', 'Жұма'), ('Сенбі', 'Сенбі'), ('Жексенбі', 'Жексенбі')], max_length=255, verbose_name='Күн'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Топтың қысқаша'),
        ),
        migrations.AlterField(
            model_name='group',
            name='filled',
            field=models.IntegerField(default=0, verbose_name='Неше оқушы бар'),
        ),
        migrations.AlterField(
            model_name='group',
            name='hours',
            field=models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00')], max_length=255, verbose_name='Сағат'),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_available',
            field=models.IntegerField(default=30, verbose_name='Максималды оқушылар саны'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Топтың аты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Оқушылар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IIN',
            field=models.CharField(max_length=20, verbose_name='ЖСН'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Қала'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(verbose_name='Туған күні'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronym',
            field=models.CharField(max_length=35, verbose_name='Әкесінің аты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Қолданушы'),
        ),
    ]
