# Generated by Django 4.0.4 on 2022-06-05 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 5, 44, 907069), verbose_name='Жабылу уақыты'),
        ),
    ]
