# Generated by Django 4.0.4 on 2022-06-05 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_group_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isCertificateAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 20, 36, 14, 643258), verbose_name='Жабылу уақыты'),
        ),
    ]
