# Generated by Django 4.0.4 on 2022-06-07 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_group_isclosed_alter_group_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 18, 9, 36, 252217), verbose_name='Біту уақыты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 18, 9, 36, 252217), verbose_name='Жабылу уақыты'),
        ),
    ]
