# Generated by Django 4.0.4 on 2022-06-07 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_group_end_date_alter_group_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 19, 17, 56, 441717), verbose_name='Жабылу уақыты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 19, 17, 56, 441717), verbose_name='Біту уақыты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Енгізілмеген', max_length=255, verbose_name='Қала'),
        ),
    ]
